### ISSUE TITLE
Deployment of dist output on other sites

### ISSUE THREAD

**Issue by tyhopp** [seriousben/embeddable-react-widget#27]
Hi @seriousben, awesome job with this project - this is a question rather than an issue. Can you give an example of how you would embed the widget into another site?

I first tried using the script on your demo site with no luck:
```
<script src="https://seriousben.github.io/embeddable-react-widget/widget.js" />
<script>
     Widget.mount();
</script>
```

And then tried cloning this project, creating a production build and deploying it from something like Netlify or Surge but wasn't able to see it rendered in the third-party site.

This might be a silly question but I thought I'd ask regardless. Thanks and again great project!

**Comment by seriousben** [comment]
Very good question.

I have seen a similar issue when [CSP] is involved or when [CORS] is not allowed on the server serving the widget.js. I suggest looking at your developer console since it normally gives you an hint on what is going on.

[CSP]: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
[CORS]: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by tyhopp** [comment]
Good call, I do believe it had to do with CSP/CORS permissions after all. For anyone else who might see this thread this is how I got it work locally:

Move the production build of `widget.js` from `dist/` to your local site. The widget will render using this:

```
<script src="./widget.js"></script>
<script>
    EmbeddableWidget.mount();
</script>
```

It doesn't solve the permissions issue, but at least proves the problem isn't with the built widget.

Thanks @seriousben  🍻
